### ISSUE TITLE
AccessError when using v13 and list_db = false

### ISSUE THREAD

**Issue by yajo** [Tardo/OdooInfo#1]
1. Fresh odoo 13.0 with website.
1. configure it with `list_db = false`
1. Browse the website. A popup with access error appears.

Error logs:

```log
Server application error
 Error code: 200 
 Error message: Odoo Server Error 
 Error data message:
 Access denied 
 Error data debug:
 Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/custom/src/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/controllers/rpc.py", line 71, in jsonrpc
    return dispatch_rpc(service, method, args)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 138, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/custom/src/odoo/odoo/service/db.py", line 446, in dispatch
    return g[exp_method_name](*params)
  File "/opt/odoo/custom/src/odoo/odoo/service/db.py", line 417, in exp_list
    raise odoo.exceptions.AccessDenied()
odoo.exceptions.AccessDenied: Access denied
ajax.js:35:25
uncaught exception: Object
```

**Comment by Tardo** [comment]
Thanks for report... it should be fixed in v3.2. Now the extension uses vanilla jQuery instead of Odoo rpc method to avoid print the errors.
